[web]
www[01:10].example.com

# www01.example.com
# www02.example.com
# www03.example.com
# ...
# www10.example.com




# www[1:50:2].example.com

# www1.example.com
# www3.example.com
# www5.example.com
# ...